name: Windows x86 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_x86:

    runs-on: windows-latest

    env:
      VERSION: "2.1.4"
      ARTIFACT: "libplctag_2.1.4_windows_x86.zip"
      BUILD: "${{ github.workspace }}/build"
      DIST: "${{ github.workspace }}/build/bin_dist"

    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir ${{ env.BUILD }}

    - name: Configure CMake
      run: cd ${{ env.BUILD }}; cmake .. -G "Visual Studio 16 2019" -A Win32

    - name: Build
      run: cd ${{ env.BUILD }}; cmake --build . --config Release

    - name: Test
      run: echo "no-op for now"

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ARTIFACT }}
        path: ${{ env.DIST }}
